default: &default
  adapter: postgresql
  encoding: unicode
  host: "localhost"
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: issues_development

test:
  <<: *default
  database: issues_test

production:
  <<: *default
  database: issues
